// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"fixed top-0 left-0 right-0 z-50 bg-gray-900/80 backdrop-blur-md border-b border-gray-800/50\"><div class=\"container mx-auto px-4 py-4 flex justify-between items-center\"><a href=\"/\" class=\"text-2xl font-light tracking-wider text-white hover:text-blue-400 transition-colors\">MIKE SHIN</a><div class=\"hidden md:flex space-x-8\"><a href=\"#projects\" class=\"text-gray-300 hover:text-white transition-colors font-medium\">Projects</a> <a href=\"#blogs\" class=\"text-gray-300 hover:text-white transition-colors font-medium\">Blog</a> <a href=\"#contact\" class=\"text-gray-300 hover:text-white transition-colors font-medium\">Contact</a></div><div class=\"flex items-center space-x-4\"><a href=\"https://github.com/skywall34\" class=\"flex items-center space-x-2 text-gray-300 hover:text-white transition-colors group\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"https://cdn.simpleicons.org/github/ffffff\" class=\"h-5 w-5 group-hover:scale-110 transition-transform\" alt=\"GitHub\"> <span class=\"hidden sm:inline font-medium\">GitHub</span></a> <a href=\"https://linkedin.com/in/shindohyun\" class=\"flex items-center space-x-2 text-gray-300 hover:text-white transition-colors group\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"/static/img/linkedin.svg\" class=\"h-5 w-5 group-hover:scale-110 transition-transform\" alt=\"LinkedIn\"> <span class=\"hidden sm:inline font-medium\">LinkedIn</span></a></div></div></nav><div class=\"h-20\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
