// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-gray-800\"><div class=\"container mx-auto px-4 py-4 flex justify-between items-center\"><a href=\"/\" class=\"text-2xl font-bold tracking-widest\">MIKE SHIN</a><div class=\"space-x-6 flex items-center\"><a href=\"https://github.com/skywall34\" class=\"flex items-center space-x-2 hover:text-white\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"https://cdn.simpleicons.org/github/ffffff\" class=\"h-5 w-5\" alt=\"GitHub\"> <span>GitHub</span></a> <a href=\"https://linkedin.com/in/shindohyun\" class=\"flex items-center space-x-2 hover:text-white\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"/static/img/linkedin.svg\" class=\"h-5 w-5\" alt=\"LinkedIn\"> <span>LinkedIn</span></a> <button class=\"p-2 rounded-full hover:bg-gray-700\"><!-- dark/light toggle icon --><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M10 2a1 1 0 011 1v2a1 1 0 11-2 0V3a1 1 0 011-1zm4.22 1.78a1 1 0 011.42 1.42l-1.42-1.42zm2.83 4.24a1 1 0 01-.71 1.7H17a1 1 0 010 2h-1.66a1 1 0 01-.71-1.7l1.42-1.42zm-4.24 4.24a1 1 0 01-1.42 1.42l-1.42-1.42a1 1 0 011.42-1.42l1.42 1.42zm-4.24 0a1 1 0 00-1.42 1.42l1.42 1.42a1 1 0 101.42-1.42L8.57 12.3zM3.5 10a1 1 0 100 2H5a1 1 0 000-2H3.5zm1.78-4.22a1 1 0 10-1.42 1.42L5.3 8.57a1 1 0 101.42-1.42L5.28 5.78zM10 14a1 1 0 00-1 1v2a1 1 0 102 0v-2a1 1 0 00-1-1z\"></path></svg></button></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
