// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Profile() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"container mx-auto px-4 py-16 md:py-24\"><div class=\"max-w-4xl mx-auto\"><div class=\"flex flex-col md:flex-row items-center md:items-start gap-8\"><div class=\"relative\"><img src=\"/static/img/avatar.png\" alt=\"Mike Shin\" class=\"h-32 w-32 md:h-40 md:w-40 rounded-full border-4 border-gray-700 shadow-2xl\"><div class=\"absolute -bottom-2 -right-2 h-6 w-6 bg-green-400 rounded-full animate-pulse border-4 border-gray-900\"></div></div><div class=\"flex-1 text-center md:text-left\"><h1 class=\"text-5xl md:text-6xl font-light text-white mb-4\">Hey, I'm <span class=\"font-medium text-blue-400\">Mike</span> <span class=\"inline-block animate-bounce\">👋</span></h1><p class=\"text-xl text-gray-400 mb-6 font-light\">Software Developer & Infrastructure Specialist</p><p class=\"text-lg text-gray-300 leading-relaxed max-w-2xl mb-8\">I'm a software developer with 7+ years of experience building scalable systems.  I specialize in backend services, real-time systems, and MLOps infrastructure. Recently, I've been exploring machine learning operations and automated deployment pipelines.</p><div class=\"flex flex-wrap gap-4 justify-center md:justify-start\"><a href=\"#projects\" class=\"bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-all transform hover:scale-105 shadow-lg\">View Projects</a> <a href=\"#blogs\" class=\"border border-gray-600 hover:border-gray-500 text-gray-300 hover:text-white px-6 py-3 rounded-lg font-medium transition-all\">Read Blog</a></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
