// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Profile() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"container mx-auto px-4 mt-8 flex flex-col md:flex-row items-center\"><img src=\"/static/img/avatar.png\" alt=\"Mike Shin\" class=\"h-32 w-32 rounded-full border-4 border-gray-800\"><div class=\"ml-6\"><h1 class=\"text-4xl font-bold\">Hey, I’m Mike <span>👋</span></h1><div class=\"mt-2 flex items-center space-x-2\"><span class=\"h-3 w-3 bg-green-400 rounded-full animate-pulse\"></span></div><p class=\"mt-4 text-gray-300 max-w-xl\">I'm a software developer with 7 years of experience and counting.  I enjoy learning new technologies and specialize in building services mostly backend and infrastructure related to real time systems. More recently I've become interested in learning more about machine learning,  especially in regards to MLOps and building systems helping to automate model training/deployment. In my free time, I either like to play video games, hang out with my beautiful wife, or work on side projects. Feel free to look at what I've been working on here!</p></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
